const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),ts=require('typescript'),{startRedis}=require('./redis-helper.cjs');
(async()=>{const redis=await startRedis();if(!redis)return;try{
const processMock={env:{UPSTASH_REDIS_REST_URL:'https://redis.test.invalid',UPSTASH_REDIS_REST_TOKEN:'test-only'}};
const module={exports:{}};const ctx={module,exports:module.exports,process:processMock,fetch:redis.fetch,Date,Math,console};vm.createContext(ctx);vm.runInContext(ts.transpileModule(fs.readFileSync('lib/store.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,ctx);const s=module.exports,uid='tester',day=new Date().toISOString().slice(0,10),yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);
await s.saveDailyChallenge(uid,day,{day,deck:['a','b','a','b'],matched:[],firstIndex:null,moves:0,score:0,status:'active',startedAt:'2026-10-07T07:00:00Z'});
let result=await s.flipDailyCard(uid,day,0,18,{moves:0,firstIndex:null});assert.equal(result.daily.firstIndex,0);assert(Array.isArray(result.daily.matched),"Lua empty matched must be an array at the API boundary");
await assert.rejects(()=>s.flipDailyCard(uid,day,1,18,{moves:0,firstIndex:null}),/state changed/);
await assert.rejects(()=>s.flipDailyCard(uid,day,0,18,{moves:0,firstIndex:0}),/visible/);
const parallel=await Promise.allSettled([s.flipDailyCard(uid,day,2,18,{moves:0,firstIndex:0}),s.flipDailyCard(uid,day,1,18,{moves:0,firstIndex:0})]);assert.equal(parallel.filter(x=>x.status==='fulfilled').length,1);assert.equal((await s.getDailyChallenge(uid,day)).moves,1);
// Regression: a mismatch must permit the next first card, including after reload.
const mismatchUid='mismatch-tester';
await s.saveDailyChallenge(mismatchUid,day,{day,attemptId:'mismatch',deck:['a','b','a','b'],matched:[],firstIndex:null,moves:0,score:0,status:'active',startedAt:new Date().toISOString()});
await s.flipDailyCard(mismatchUid,day,0,18,{moves:0,firstIndex:null,attemptId:'mismatch'});
const mismatch=await s.flipDailyCard(mismatchUid,day,1,18,{moves:0,firstIndex:0,attemptId:'mismatch'});
assert.equal(mismatch.reveal.matched,false);assert.equal(mismatch.daily.moves,1);assert.equal(mismatch.daily.firstIndex,null);
const resumed=await s.getDailyChallenge(mismatchUid,day);
const third=await s.flipDailyCard(mismatchUid,day,2,18,{moves:resumed.moves,firstIndex:resumed.firstIndex,attemptId:resumed.attemptId});
assert.equal(third.reveal.value,'a');assert.equal(third.daily.moves,1);assert.equal(third.daily.firstIndex,2);
// Atomic best result never regresses under concurrent completed/status reconciliation.
await Promise.all([s.recordDailyResult(uid,day,{moves:6,score:100,completedAt:'fixed'}),s.recordDailyResult(uid,day,{moves:9,score:50,completedAt:'later'})]);assert.equal((await s.getDailyBest(uid,day)).moves,6);await s.recordDailyResult(uid,day,{moves:6,score:100,completedAt:'new'});assert.equal((await s.getDailyBest(uid,day)).completedAt,'fixed');
await s.recordDailyCompletion(uid,yesterday);await Promise.all([s.recordDailyCompletion(uid,day),s.recordDailyCompletion(uid,day)]);assert.equal((await s.getDailyMeta(uid,day)).streak.count,2);await s.recordDailyCompletion(uid,yesterday);assert.equal((await s.getDailyMeta(uid,day)).streak.lastDay,day);
await Promise.all(Array.from({length:3},()=>s.recordMetric(day,'subject','daily_completed','receipt',60)));const report=(await s.getMetricsReport(90)).find(r=>r.day===day);assert.equal(report.events.daily_completed,1);assert.equal(report.dailyDurationCount,1);assert.equal(report.dailyDurationSum,60);
// Real Lua entitlement replay and response-loss fault injection.
await s.grantPremium(uid,'premium-test');await s.grantPremium(uid,'premium-test');assert.equal(await s.hasPremium(uid),true);await s.grantReplayCredit(uid,'replay-test');await s.grantReplayCredit(uid,'replay-test');assert.equal(await s.getReplayCredits(uid),1);
let lost=false;ctx.fetch=async(url,o)=>{const r=await redis.fetch(url,o);const a=JSON.parse(o.body);if(!lost&&a[0]==='EVAL'&&a[2]===3&&a[1].includes('fulfilled')){lost=true;throw Error('Response lost after commit')}return r};
await assert.rejects(()=>s.grantReplayCredit(uid,'lost-replay'),/Response lost/);await s.grantReplayCredit(uid,'lost-replay');assert.equal(await s.getReplayCredits(uid),2);
ctx.fetch=redis.fetch;await Promise.all([s.grantReplayCredit(uid,'concurrent-replay'),s.grantReplayCredit(uid,'concurrent-replay')]);assert.equal(await s.getReplayCredits(uid),3);await assert.rejects(()=>s.grantReplayCredit('other','concurrent-replay'),/another user/);
let lock=await s.acquireDailyLock(uid,day);const newState={day,deck:['x','x'],matched:[],firstIndex:null,moves:0,score:0,status:'active'};await s.resetDailyChallenge(uid,day,newState,lock);assert.equal(await s.getReplayCredits(uid),2);assert.equal((await s.getDailyChallenge(uid,day)).moves,0);
await s.releaseDailyLock(uid,day,lock);await assert.rejects(()=>s.resetDailyChallenge(uid,day,newState,lock),/expired/);assert.equal(await s.getReplayCredits(uid),2);
lock=await s.acquireDailyLock(uid,day);await redis.command(['SET','arena:daily-attempts:'+day+':'+uid,'bad']);await assert.rejects(()=>s.resetDailyChallenge(uid,day,newState,lock),/review/);assert.equal(await s.getReplayCredits(uid),2);await s.releaseDailyLock(uid,day,lock);
// Start response loss is recoverable without creating a second attempt.
const freshUid='start-tester';let startLock=await s.acquireDailyLock(freshUid,day);ctx.fetch=async(url,o)=>{const r=await redis.fetch(url,o),a=JSON.parse(o.body);if(a[0]==='EVAL'&&a[1].includes('if current then'))throw Error('Start reply lost');return r};await assert.rejects(()=>s.startDailyChallenge(freshUid,day,newState,startLock),/reply lost/);ctx.fetch=redis.fetch;await s.startDailyChallenge(freshUid,day,newState,startLock);assert.equal((await s.getDailyMeta(freshUid,day)).attempts,1);await s.releaseDailyLock(freshUid,day,startLock);await assert.rejects(()=>s.startDailyChallenge(freshUid,day,newState,startLock),/expired/);
// A late previous-attempt reset/flip cannot spend another credit or change the new board.
await s.grantReplayCredit('attempt-tester','attempt-credit');await s.grantReplayCredit('attempt-tester','attempt-credit2');await s.saveDailyChallenge('attempt-tester',day,{...newState,attemptId:'old'});const attemptLock=await s.acquireDailyLock('attempt-tester',day);ctx.fetch=async(url,o)=>{const r=await redis.fetch(url,o),a=JSON.parse(o.body);if(a[0]==='EVAL'&&a[2]===4)throw Error('Reset reply lost');return r};await assert.rejects(()=>s.resetDailyChallenge('attempt-tester',day,{...newState,attemptId:'new'},attemptLock,'old'),/reply lost/);ctx.fetch=redis.fetch;await assert.rejects(()=>s.resetDailyChallenge('attempt-tester',day,{...newState,attemptId:'newer'},attemptLock,'old'),/attempt changed/);assert.equal(await s.getReplayCredits('attempt-tester'),1);await assert.rejects(()=>s.flipDailyCard('attempt-tester',day,0,18,{moves:0,firstIndex:null,attemptId:'old'}),/attempt changed/);await s.releaseDailyLock('attempt-tester',day,attemptLock);
// Full handler -> real Lua -> public response: empty arrays survive first flip/status.
const apiUid='api-tester',apiCtx={require:p=>p==='crypto'?require('crypto'):p.endsWith('/pi')?{arenaSessionFromRequest:()=>null,bearerFromRequest:()=> 'test',verifyAccessToken:async()=>({uid:apiUid})}:p.endsWith('/metrics')?{safeRecordMetric:async()=>true}:s,Date,Math,Set};vm.createContext(apiCtx);vm.runInContext(fs.readFileSync('pages/api/game-state.ts','utf8').replace('export default async function handler','async function handler'),apiCtx);
async function call(action,index){const res={setHeader(){},status(n){this.code=n;return this},json(data){this.data=data;return this}};await apiCtx.handler({method:'POST',body:{action,index,day}},res);assert.equal(res.code,200,JSON.stringify(res.data));return res.data;}
await s.saveDailyChallenge(apiUid,day,{...newState,startedAt:new Date().toISOString()});let apiResponse=await call('daily-flip',0);assert(Array.isArray(apiResponse.daily.matched));assert.equal(apiResponse.daily.matches,0);assert(!('deck' in apiResponse.daily));apiResponse=await call('daily-status');assert.equal(apiResponse.daily.firstIndex,0);await call('daily-flip',1);assert.equal((await call('daily-status')).daily.status,'completed');
await s.savePvpMatch({id:'test-match',status:'active',deck:['x','x'],players:[{uid:apiUid,matched:[],firstIndex:null,moves:0,score:0,status:'active'},{uid:'bot',bot:true,matched:[],firstIndex:null,moves:0,score:0,status:'completed'}]});await s.setUserPvpMatch(apiUid,'test-match');apiResponse=await call('pvp-flip',0);assert(Array.isArray(apiResponse.pvp.own.matched));apiResponse=await call('pvp-status');assert(Array.isArray(apiResponse.pvp.own.matched));
console.log('Real Redis: Daily state preconditions, concurrent tap, best-result/streak idempotence, Lua telemetry dedupe and entitlement replay passed.');
}finally{await redis.stop()}})().catch(e=>{console.error(e);process.exitCode=1});
